### ISSUE TITLE
Entities does not (always) load after reboot

### ISSUE THREAD

**Issue by f00dagi** [icanos/hassio-plejd#31]
Hi!

Thanks for your development. You seem quite busy with this add-on already and this might be a minor thing but I might as well report it.

About half of the times I reboot the Plejd entities are not loaded into hassio. Either I reboot again and hope for the best or I manually restart mqtt and/or the plejd add-on and then the entities are loaded propery.

I am on a Raspberry 4, 0.103.6, 0.2.0.

**Comment by icanos** [comment]
Can't say that I've seen that myself. Have you made sure that you've added the birth_message to your MQTT configuration?

**Comment by f00dagi** [comment]
Do you mean in 
1) mqtt configuration in the mosquitto broker add-on? 
or 
2) in the mqtt: in configuration.yaml. 

I have this in the 2)...
mqtt:
  birth_message: 
    topic: 'hass/status'
    payload: 'online'
  will_message: 
    topic: 'hass/status'
    payload: 'offline'

**Comment by icanos** [comment]
My mqtt: config in `configuration.yaml` looks like:

```
mqtt:
  broker: <ip address>
  username: <username>
  password: <password>
  client_id: hassio
  discovery: true
  discovery_prefix: homeassistant
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'
```

I suspect that you need to add `discovery: true` to your config.

**Comment by f00dagi** [comment]
I should have been more clear. This is my complete mqtt code in configuration.yaml

```
mqtt:
  broker: 192.168.1.242
  username: hassio
  password: hassio
  client_id: mqtt
  discovery: true
  discovery_prefix: homeassistant
  birth_message: 
    topic: 'hass/status'
    payload: 'online'
  will_message: 
    topic: 'hass/status'
    payload: 'offline'
```
