### ISSUE TITLE
Switch / Light

### ISSUE THREAD

**Issue by Mikro007** [icanos/hassio-plejd#5]
I´m not shure if this is an error, but I write about it anyway.

All the items that the app found comes up as light. 

Is it possible to make the dim-01 to light and ctr-01 to switch?

I have waiting for this add-on! Great work!!!

**Comment by icanos** [comment]
Currently, it's hardcoded to be a light, I suppose its possible introduce somekind of override for specific items to be a switch instead. Need to give that some thought, any input on how it could be done in an easy way?

**Comment by axlthorell** [comment]
I use this in my configuration.yaml to convert switches into lights. 
I have IKEA smart plugs that I want my Google Home to see as lights, perhaps it can be done in reverse?

```
## Turn switch into light
light:
  - platform: switch
    name: My light
    entity_id: switch.my_switch

```
