### ISSUE TITLE
DIM-2 and MQTT auto discover issue?

### ISSUE THREAD

**Issue by mattiasjonsson** [icanos/hassio-plejd#6]
MQTT auto discover does not list input 2 of DIM-2 devices. The MQTT broker does however receive topics/messages from both inputs of the device.

**Comment by icanos** [comment]
Are the inputs identically named in the Plejd app? Otherwise they should appear in HA.

**Comment by mattiasjonsson** [comment]
True. I checked the names and of course they had the same identical name. Sorry for bother you about this issue. I should have thought of that myself. ;)

Another question: Is it possible to add the entities by hand in the configuration.yaml? And If so, how would I go about doing that?

**Comment by icanos** [comment]
Nothing to worry about :) in what scenario do you need to add devices to the config? It would need to know the Plejd device id which is fetched from the API.

**Comment by mattiasjonsson** [comment]
I needed to be able to change the entity ids and have more overall control. I managed to solve it.
Turned off MQTT auto discovery and just added the Plejd devices as MQTT lights like this:

```
light:
  platform: mqtt
  name: "plejd_kok_kokso"
  unique_id: "light.plejd.kok_kokso"
  state_topic: "homeassistant/light/plejd/18/state"
  command_topic: "homeassistant/light/plejd/18/set"
  brightness_state_topic: "homeassistant/light/plejd/18/brightness"
  brightness_command_topic: "homeassistant/light/plejd/18/setBrightness"
  payload_on: 1
  payload_off: 0
  optimistic: false
```
