### ISSUE TITLE
Http error on line 1

### ISSUE THREAD

**Issue by atrampare** [icanos/hassio-plejd#7]
Im having trouble setting up the addon. I dont get any entities showing up. 
When i look at the log for the plejd app in hass.io addon section. The log says there is an http error on line 1. But it also says its Connected to plejd at the end. The mqtt log looks fine. 
Might be that i have the wrong http to mqtt in the config.yaml. What should that be with mqtt running directly för om hass.io?

Im not at home at the moment. But i can publish the logs tonight.

**Comment by axlthorell** [comment]
Hi. My configuration.yaml looks like this
## MQTT
```
mqtt:
  broker: localhost
  username: mqtt
  password: !secret mqtt_password
  client_id: mqtt
  discovery: true
  discovery_prefix: homeassistant
  birth_message: 
    topic: 'hass/status'
    payload: 'online'
  will_message: 
    topic: 'hass/status'
    payload: 'offline'
```
I have a user set up with the username mqtt and the password for the user stored in secrets.yaml.
My configuration of the add-on looks like this
```
{
  "site": "My site name",
  "username": "my@email.com",
  "password": "secretplejdpassword",
  "mqttBroker": "mqtt://localhost",
  "mqttUsername": "mqtt",
  "mqttPassword": "mqttuserspassword"
}
```

The http error shows up in my log and it is working anyway.
